/* Book Actions */
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';

export const FETCH_BOOK_DEADLINE_SUCCESS = 'FETCH_BOOK_DEADLINE_SUCCESS';

export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';

export const SAVE_BOOK_DEADLINE_SUCCESS = 'SAVE_BOOK_DEADLINE_SUCCESS';

export const SAVE_BOOK_SUCCESS = 'SAVE_BOOK_SUCCESS';

/* Home Actions */
export const SET_HOME_VIEW = 'SET_HOME_VIEW';
